In [1]:
import numpy as np

In [2]:
np.random.randn(4)

array([-0.07827544,  1.09553006, -0.62761442, -1.01931271])

In [3]:
np.empty((0, 3))

array([], shape=(0, 3), dtype=float64)

In [4]:
x = [2,3,1]
x.index(1)

2

In [7]:
X = np.random.randint(1, 10, size = (10, 4))
X

array([[4, 2, 4, 3],
       [1, 5, 1, 8],
       [8, 9, 3, 1],
       [8, 2, 9, 3],
       [9, 4, 3, 3],
       [6, 5, 8, 9],
       [1, 3, 5, 6],
       [5, 6, 6, 1],
       [2, 2, 8, 4],
       [2, 6, 6, 3]])

In [23]:
y = np.random.randint(1, 4, size = (10, 1))
y

array([[1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [2],
       [3],
       [1],
       [2]])

In [25]:
X[5].item()

ValueError: can only convert an array of size 1 to a Python scalar

In [15]:
for x_i in X:
    print(x_i, np.argsort(x_i), x_i[np.argsort(x_i)[:2]])
    print(x_i.item())

[4 2 4 3] [1 3 0 2] [2 3]


ValueError: can only convert an array of size 1 to a Python scalar

In [14]:
X.item()

ValueError: can only convert an array of size 1 to a Python scalar

In [29]:
np.sqrt(X[0].T.dot(X[4]))

8.06225774829855

In [34]:
X[0] - X[4]

array([-5, -2,  1,  0])

In [36]:
X.shape

(10, 4)

In [37]:
y.size

10

In [39]:
np.ndarray((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
query_point = (2, 2)
query = np.array(query_point)
query

array([2, 2])

In [42]:
type(query)

numpy.ndarray

In [46]:
np.array([(1, 2), (1, 4), (1, 0), (10, 2), (10, 4), (10, 0)])

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0]])

In [52]:
a = np.array([3,5,0,2])
np.argmin(a)

2

In [53]:
y_true2 = np.array([[0.5, 1], [-1, 1], [7, -6]]) 
y_pred2 = np.array([[0, 2], [-1, 2], [8, -5]])

In [59]:
np.mean((y_true2 - y_pred2) ** 2)

0.7083333333333334