## Binary Classification with Logistic Regression
Easy
Machine Learning

Implement the prediction function for binary classification using Logistic Regression. Your task is to compute class probabilities using the sigmoid function and return binary predictions based on a threshold of 0.5.

Example:
Input:


In [ ]:
'''
Clarify:
- can I assume we have the input data of all numerical features?

'''

In [11]:
import numpy as np

def predict_logistic(X: np.ndarray, weights: np.ndarray, bias: float) -> np.ndarray:
	"""
	Implements binary classification prediction using Logistic Regression.

	Args:
		X: Input feature matrix (shape: N x D)
		weights: Model weights (shape: D)
		bias: Model bias

	Returns:
		Binary predictions (0 or 1)
	"""
	# Your code here
	z = X @ weights + bias
	sigmoids = 1 / (1 + np.exp(-z))  # sigmoid activation
	y_pred = np.where(sigmoids >= 0.5, 1, 0)  # threshold at 0.5
	return y_pred

In [12]:
predict_logistic(np.array([[1, 1], [2, 2], [-1, -1], [-2, -2]]), np.array([1, 1]), 0)
# Output: [1 1 0 0]

array([1, 1, 0, 0])

In [2]:
import numpy as np

X = np.array([[1, 1], [2, 2], [-1, -1], [-2, -2]])
weights = np.array([1, 1])
bias = 0
z = X @ weights + bias
z

array([ 2,  4, -2, -4])

In [3]:
z.shape

(4,)

In [5]:
sigmoids = 1 / (1 + np.exp(-z))  # sigmoid activation
sigmoids.shape

(4,)

In [6]:
y_pred = np.where(sigmoids >= 0.5, 1, 0)  # threshold at 0.5
y_pred

array([1, 1, 0, 0])